import axios from "axios";
import { GetServerSidePropsContext } from "next";
import Head from "next/head";
import React, { useContext, useEffect, useRef, useState } from "react";
import TodolistView from "../src/components/TodolistView/TodolistView";
import TodoList from "../src/entities/Todolist";
import useTodoListHook from "../src/presenters/useTodoListHook";
import styles from "../styles/Home.module.css";
import { TodolistContext, TodolistProvider } from "../src/contexts/TodolistContext";
type Item = {
	id: string;
	description: string;
	done: boolean;
};
type homeProps = {
	data: Item[];
};

function Footer() {

	const [todos, todosDispatch] = useContext(TodolistContext)!;
	return (
		<div>
			{todos.length}
		</div>
	)
}
export default function Home(props: homeProps) {
	const [todo, setTodo] = useState<string>("");
	const [todos, todosDispatch] = useContext(TodolistContext)!;

	const handleEnter = (e: React.KeyboardEvent<HTMLInputElement>) => {
		if (e.key == "Enter") {
			const description = e.currentTarget.value;
			if (!description) return;
			todosDispatch("create", { description });
			setTodo("");
		}
	};

	const handleToggle = (e: React.MouseEvent<HTMLSpanElement, MouseEvent>) => {
		const id = e.currentTarget.dataset.key!;
		todosDispatch("toggle", { id });
	};

	const handleDelete = (e: React.FormEvent<HTMLSpanElement>) => {
		const id = e.currentTarget.dataset.key;
		console.log(id);
		todosDispatch("remove", { id });
	};

	return (
		<div className={styles.container}>
			<Head>
				<title> </title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<h1 className={styles.title}>TodoList</h1>
			<Footer />
			<main className={styles.main}>
				<div>
					<input
						type="text"
						name="todo"
						id="todo"
						value={todo}
						onChange={(e) => setTodo(e.target.value)}
						onKeyUp={handleEnter}
					/>
				</div>
				<div>
					<hr />
				</div>
				<div className="todo-list-view">
					{todos.map((item) => (
						<TodolistView
							key={item.id.toString()}
							item={item}
							ontoggle={handleToggle}
							ondelete={handleDelete}
						/>
					))}
				</div>
			</main>
		</div>
	);
}

export const getServerSideProps = async (
	context: GetServerSidePropsContext
) => {
	// console.log(process.env.NEXT_PUBLICAPI);
	const response = await fetch("http://localhost:3000/api/todos");
	const todos: Item[] = await response.json();
	// console.log("backend:", todos);
	return {
		props: {
			data: todos,
		},
	};
};
